### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by Containability** [gaih/introduction-to-python#8]
Merhaba, ödevi yaptım ancak 0 ile 1000 aralığında yaptım bir aralık belirleyerek yapmam sıkıntı olur mu? Bir de ödevi direk olarak HW1.py olan hazır dosyaya yapıştırdım öyle commitledim sorun olmaz değil mi?

**Comment by mertmtn** [comment]
1. ödevde random prime number 3x3 matrixi istenmiş ama ödevde eksik bir şey var? bu prime number en fazla kaç olabilir? İnternette 4bit - 8bit gibi bir seçenek var. Arkadaş ödevinde aralık belirtmiş. Random numberda aralık belirtilebilir mi?
